CREATE OR REPLACE DATABASE MANAGE_DB;

USE DATABASE MANAGE_DB;
CREATE SCHEMA EXTERNAL_STAGES;

USE SCHEMA EXTERNAL_STAGES;

CREATE STAGE 01_EVENTS
    URL = "s3://01-open-data";

LIST @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS;

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.01_EVENTS;

ALTER STAGE MANAGE_DB.EXTERNAL_STAGES.01_EVENTS;
    SET CREDENTIALS=(aws_key_id='cab' aws_secret_key='123')
