CREATE OR REPLACE TABLE 01_DATABASE.EVENTS.EVENTS_URL AS
SELECT 
    $1::INT ID, --COMO SE FOSSE: cast() 
    TO_DATE($2, 'YYYYMMDD') SQLDATE,
    $3 MONTH_YEAR,
    $10 SOURCE_URL
FROM @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS/events/20250101.export.csv
(file_format => MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT);

COPY INTO 01_DATABASE.EVENTS.EVENTS_URL FROM
SELECT 
    $1::INT ID, --cast() 
    TO_DATE($2, 'YYYYMMDD') SQLDATE,
    $3 MONTH_YEAR,
    $10 SOURCE_URL
FROM @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS/events/20250101_02.export.csv
(file_format => MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT);