CREATE DATABASE 01_DATABASE;

CREATE SCHEMA EVENTS;

CREATE TABLE IF NOT EXISTS 01_DATABASE.EVENTS.EVENTS_FULL (

    COLUMN_01 INT,
    COLUMN_02 varchar,
    ...
);

COPY INTO 01_DATABASE.EVENTS.EVENTS_FULL
    --FROM @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS/events/20250101.export.csv
    FROM @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS/events
    file_format = (type = 'csv' field_delimiter = '\t')
    pattern = '.*20250101.*';

SELECT *
FROM 01_DATABASE.EVENTS.EVENTS_FULL;