-- Criar STAGE, criar 


CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGE.SNOWFLAKE_01
    URL = 's3://snowflake-series'
    STORAGE_INTEGRATION = S3_INTEGRATION;

LIST @MANAGE_DB.EXTERNAL_STAGE.SNOWFLAKE_01;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.JSON_FMT
    TYPE = JSON_FMT

CREATE DATABASE MEDIAS;

CREATE SCHEMA MEDIAS.YOUTUBE;

CREATE OR REPLACE TABLE MEDIAS.STATISTICS_RAW {
    raw_file variant
};

COPY INTO MEDIAS.YOUTUBE.STATISTICS_RAW
    FROM @MANAGED_DB.EXTERNAL_STAGES.SNOWFLAKE_01
    file_format = MANAGE_DB.FLE_FORMATS.JSON_FMT
    file = {youtube_data.json}

SELECT * FROM MEDIAS.YOUTUBE.STATISTICS_RAW;