CREATE OR REPLACE SCHEMA FILE_FORMATS;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT
    FIELD_DELIMITER = '\t'
    TYPE = CSV
    --SKIP_HEADER=1;

DESC FILE FORMAT FILE_FORMATS.CSV_TAB_FMT;

LIST STAGE @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS/events/;

COPY INTO 01_DATABASE.EVENTS.EVENTS_FULL
    --FROM @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS/events/20250101.export.csv
    FROM @MANAGE_DB.EXTERNAL_STAGES.01_EVENTS/events/20200101.export.csv
    --file_format = (FORMAT_NAME = MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT , SKIP_HEADER = 1)
    file_format = MANAGE_DB.FILE_FORMATS.CSV_TAB_FMT