

CREATE SCHEMA MANAGE_DB.STORAGE_INTEGRATION;

USE DATABASE MANAGE_DB
USE SCHEMA STORAGE_INTEGRATION; 

-- NEED TO CREATE A AWS ROLE TO GET THE ARN
CREATE OR REPLACE STORAGE INSTEGRATION S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ARN = 'arn::aws:iam::1568616:role/path...'
    STORAGE_ALLOWED_LOCATIONS = ('s3://snowflake-series')
    COMMNET = 'intregration';

    DESC INSTEGRATION S3_INTEGRATION
    -- Get STORAGE_AWS_EXTERNAL_ID and PUT to "sts:ExternalId"
    -- Get STORAGE_AWS_IAM_USER_ARN and EDIT to "Principal":{"AWS":""},
